services:
  spark-lab:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - THREADS=${THREADS}
      - DRIVER_MEMORY=${DRIVER_MEMORY}
      - SHUFFLE_PARTITIONS=${SHUFFLE_PARTITIONS}
    volumes:
      - ./data:/app/data
    # keep container running, only for development
    command: tail -f /dev/null
